import html
from datetime import datetime, timezone

from fastapi import APIRouter, Depends
from fastapi.responses import HTMLResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import OPS_ROLES, require_roles
from app.db.session import get_db
from app.models import RiskCell, Zone

router = APIRouter(prefix="/briefing", tags=["briefing"])

# WeasyPrint is optional at scaffold time; HTML is print-to-PDF ready either way.
try:
    from weasyprint import HTML as _WeasyHTML  # noqa: F401

    HAS_WEASYPRINT = True
except Exception:  # pragma: no cover
    HAS_WEASYPRINT = False


@router.post("/pdf")
async def briefing_pdf(district: str, lang: str = "en",
                       db: AsyncSession = Depends(get_db), _user=Depends(require_roles(*OPS_ROLES))):
    zones = (
        await db.execute(select(Zone).where(Zone.district == district))
    ).scalars().all()
    rows = []
    for z in zones:
        cell = await db.get(RiskCell, z.id)
        level = cell.hazard_level if cell else 0
        rows.append((z.zone_code, z.name or "-", z.population or 0, z.susc_mean or 0, level))
    rows.sort(key=lambda r: -r[4])

    trs = "".join(
        f"<tr class='lv{lv}'><td>{html.escape(code)}</td><td>{html.escape(name)}</td>"
        f"<td>{pop:,}</td><td>{susc:.0f}</td><td><b>L{lv}</b></td></tr>"
        for code, name, pop, susc, lv in rows[:20]
    )
    now = datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")
    doc = f"""<!doctype html><html><head><meta charset="utf-8">
<style>
  body {{ font-family: 'Noto Sans', 'Noto Sans Bengali', 'Noto Sans Devanagari', sans-serif; margin: 32px; color:#0B1220; }}
  h1 {{ font-size: 22px; }} .meta {{ color:#475569; font-size: 12px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 16px; font-size: 13px; }}
  th, td {{ border: 1px solid #CBD5E1; padding: 6px 8px; text-align: left; }}
  th {{ background: #0B1220; color: white; }}
  tr.lv3 td {{ background: #FEE2E2; }} tr.lv4 td {{ background: #EDE9FE; }} tr.lv2 td {{ background: #FFEDD5; }}
  .foot {{ margin-top: 24px; font-size: 11px; color:#64748B; }}
</style></head><body>
<h1>BhuRakshak - Daily Risk Briefing</h1>
<div class="meta">District: {html.escape(district)} &middot; Generated {now} &middot; Language: {html.escape(lang)}</div>
<table><thead><tr><th>Zone</th><th>Name</th><th>Population</th><th>Susceptibility</th><th>Hazard</th></tr></thead>
<tbody>{trs}</tbody></table>
<div class="foot">Top-20 response priority (hazard x exposure). Auto-generated by BhuRakshak - verify with district admin before public release.</div>
</body></html>"""

    if HAS_WEASYPRINT:
        from weasyprint import HTML

        pdf = HTML(string=doc).write_pdf()
        return HTMLResponse(content=pdf, media_type="application/pdf", headers={
            "Content-Disposition": f"attachment; filename=briefing_{district.replace(' ', '_')}.pdf"
        })
    return HTMLResponse(content=doc)
