"""prepare.py - BhuRakshak Autoresearch Data Preparation Engine
SIH26001: AI-Based Early Warning and Landslide Risk Monitoring System in NER.

This file builds and caches the immutable ground-truth datasets for:
1. Model A: Landslide Susceptibility (Leave-One-District-Out Spatial CV)
2. Model B: Hazard Nowcast (Temporal Split: <=2019 Train / 2020-22 Val / 2023-24 Test)

==============================================================================
!!  THESE DATASETS ARE SYNTHETIC. THEY CONTAIN NO REAL LANDSLIDE RECORDS.  !!
==============================================================================

Both label vectors are generated by this very file:

  * Model A -- rows are drawn from two hand-separated distributions (steep /
    concave / low-NDVI for positives, gentle / vegetated for negatives) and the
    label is simply which distribution the row came from. A learner that
    recovers the generator's parameter choices scores AUC 1.0.

  * Model B -- ``p_fail`` is evaluated from the logistic written at
    :func:`build_hazard_nowcast_dataset`, then ``y`` is a Bernoulli draw from
    it. The "ground truth" is therefore the script's own formula.

The consequence is that every metric produced from these files -- LODO AUC,
AP, POD, FAR, CSI, and the composite score in ``best_result.json`` -- measures
a model's ability to re-derive this file's arithmetic. It is a test of
optimiser plumbing, not of landslide prediction. A perfect score here is the
expected outcome and carries no information about field skill.

`fetch_or_synthesize_weather()` is also **decorative**: its return value is
printed in ``main()`` and then discarded. Neither dataset builder consumes it,
so "Successfully loaded N real hourly records" in the log does not mean any
real record reached a training matrix.

These datasets are useful for one thing only: verifying that the training,
CV-splitting, calibration and scoring code runs end to end. Use them for that.
Never quote their scores as evidence of model quality, and never ship a model
trained on them to the API -- ``risk_engine.get_model_b_bundle()`` rejects any
bundle carrying ``synthetic: true``.

DO NOT MODIFY DURING AUTORESEARCH LOOPS. This file defines the fixed benchmark truth.
"""

from datetime import datetime, timezone
import json
import math
import os
from pathlib import Path
import sys
import zlib

import numpy as np
import requests

DATA_DIR = Path(__file__).resolve().parent / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

DISTRICTS = ["aizawl", "east_khasi_hills", "noney_imphal_west", "gangtok"]
DISTRICT_COORDS = {
    "aizawl": {"lat": 23.73, "lon": 92.72, "monsoon_factor": 1.0, "elev_mean": 1100},
    "east_khasi_hills": {"lat": 25.45, "lon": 91.60, "monsoon_factor": 2.2, "elev_mean": 1490},
    "noney_imphal_west": {"lat": 24.90, "lon": 93.87, "monsoon_factor": 1.15, "elev_mean": 1250},
    "gangtok": {"lat": 27.42, "lon": 88.55, "monsoon_factor": 1.4, "elev_mean": 1650},
}

SUSCEPTIBILITY_FEATURES = [
    "slope_deg", "aspect_sin", "aspect_cos", "elevation_m", "plan_curv", "profile_curv",
    "twi", "spi", "tpi", "dist_stream_km", "dist_ridge_km", "dist_roadcut_m",
    "lithology_class", "landcover_class", "ndvi_mean", "ndvi_trend_5yr",
    "mean_annual_rain_mm", "monsoon_rain_normal_mm", "landslide_density_1km",
    "soil_type", "road_density_km_km2", "settlement_density", "fault_dist_km", "ndvi_std",
]

HAZARD_FEATURES = [
    "rain_1h", "rain_24h", "rain_48h", "rain_72h", "rain_7d", "eff_rain",
    "soil_moisture", "susc_mean", "susc_p90", "susc_high_frac", "seismic_flag",
    "verified_reports_7d",
]

HALF_LIFE_HOURS = 48.0


def compute_effective_rainfall(hourly_mm: np.ndarray, half_life_h: float = HALF_LIFE_HOURS) -> np.ndarray:
    """Kohler-Linsley Antecedent Precipitation Index (API) with exponential decay."""
    decay = 0.5 ** (1.0 / half_life_h)
    eff = np.zeros_like(hourly_mm, dtype=np.float32)
    acc = 0.0
    for i, mm in enumerate(hourly_mm):
        acc = acc * decay + float(mm)
        eff[i] = acc
    return eff


def fetch_or_synthesize_weather(district: str, days: int = 365 * 10, seed: int = 42) -> tuple[np.ndarray, np.ndarray]:
    """Fetch 10 years of hourly rainfall and soil moisture from Open-Meteo, with physics-based fallback."""
    cfg = DISTRICT_COORDS[district]
    lat, lon = cfg["lat"], cfg["lon"]
    end_date = "2024-12-31"
    start_date = "2015-01-01"
    url = (
        f"https://archive-api.open-meteo.com/v1/archive?"
        f"latitude={lat}&longitude={lon}&hourly=precipitation,soil_moisture_3_to_9cm&"
        f"start_date={start_date}&end_date={end_date}&timezone=UTC"
    )
    try:
        print(f"Fetching Open-Meteo weather for {district} ({lat}, {lon})...")
        resp = requests.get(url, timeout=15)
        if resp.status_code == 200:
            data = resp.json()
            if "hourly" in data and "precipitation" in data["hourly"]:
                rain = np.nan_to_num(np.array(data["hourly"]["precipitation"], dtype=np.float32), nan=0.0)
                soil = data["hourly"].get("soil_moisture_3_to_9cm")
                if soil is not None and len(soil) == len(rain):
                    soil = np.nan_to_num(np.array(soil, dtype=np.float32), nan=30.0)
                else:
                    soil = np.clip(25.0 + rain * 2.5, 5.0, 95.0)
                print(f"  Successfully loaded {len(rain)} real hourly records for {district}.")
                return rain, soil
    except Exception as exc:
        print(f"  Note: Real weather pull for {district} failed ({exc}). Using deterministic physical simulation.")

    # High-fidelity physical simulation fallback.
    #
    # crc32, not hash(): Python randomises str hashing per process unless
    # PYTHONHASHSEED is pinned, so `hash(district)` silently gave every run a
    # different fallback series. Autoresearch compared candidate models against
    # a benchmark that moved underneath them, which makes "this change improved
    # the score" unfalsifiable.
    rng = np.random.default_rng(seed + zlib.crc32(district.encode()) % 10000)
    n_hours = days * 24
    hours = np.arange(n_hours)
    day_of_year = (hours // 24) % 365
    
    # NER monsoon peaks June-September (days 150-275)
    is_monsoon = ((day_of_year >= 150) & (day_of_year <= 275)).astype(np.float32)
    monsoon_factor = cfg["monsoon_factor"]
    
    # Storm events generation via compound Poisson-Gamma distribution
    storm_intensity = rng.gamma(shape=0.45, scale=4.0, size=n_hours).astype(np.float32)
    rain = storm_intensity * is_monsoon * monsoon_factor
    # Random off-monsoon cyclonic depressions / pre-monsoon convective showers
    pre_monsoon = ((day_of_year >= 90) & (day_of_year < 150)).astype(np.float32)
    rain += rng.gamma(0.2, 2.5, size=n_hours).astype(np.float32) * pre_monsoon * 0.4
    
    rain = np.maximum(rain, 0.0)
    
    # Soil moisture dynamics with capacitance and percolation
    soil = np.zeros(n_hours, dtype=np.float32)
    cur_soil = 35.0
    for t in range(n_hours):
        # Infiltration from rain + drying exponential
        cur_soil = cur_soil * 0.996 + float(rain[t]) * 1.8
        cur_soil = min(max(cur_soil, 10.0), 98.0)
        soil[t] = cur_soil + rng.normal(0, 1.2)
    soil = np.clip(soil, 5.0, 100.0)
    
    return rain, soil


def build_susceptibility_dataset(n_samples_per_district: int = 5000, seed: int = 101) -> dict:
    """Builds spatial dataset with 24 terrain/geology/cover features across the 4 pilot districts."""
    rng = np.random.default_rng(seed)
    X_list, y_list, group_list = [], [], []
    
    for group_idx, dist in enumerate(DISTRICTS):
        cfg = DISTRICT_COORDS[dist]
        elev_base = cfg["elev_mean"]
        
        # 25% positive landslide failure cells, 75% negative stable cells
        n_pos = int(n_samples_per_district * 0.25)
        n_neg = n_samples_per_district - n_pos
        
        # Positives: steep slopes (30-55 deg), concave profile, high TWI, high roadcut proximity, low NDVI
        pos_slope = rng.normal(38.5, 7.0, n_pos).clip(15.0, 65.0)
        pos_aspect = rng.uniform(0, 2 * math.pi, n_pos)
        pos_elev = rng.normal(elev_base, 280, n_pos).clip(200, 3500)
        pos_plan_curv = rng.normal(-0.15, 0.4, n_pos)  # concave
        pos_prof_curv = rng.normal(0.22, 0.4, n_pos)   # convex acceleration
        pos_twi = rng.normal(7.8, 1.5, n_pos).clip(3.0, 14.0)
        pos_spi = rng.normal(10.2, 2.2, n_pos).clip(2.0, 18.0)
        pos_tpi = rng.normal(1.2, 2.8, n_pos)
        pos_dist_stream = np.abs(rng.normal(0.25, 0.18, n_pos))
        pos_dist_ridge = np.abs(rng.normal(0.35, 0.22, n_pos))
        pos_dist_roadcut = np.abs(rng.normal(18.0, 12.0, n_pos))  # near cut-slopes
        pos_litho = rng.integers(0, 6, n_pos).astype(np.float32)  # shale, phyllite, sandstone
        pos_landcover = rng.integers(0, 8, n_pos).astype(np.float32)
        pos_ndvi = rng.normal(0.32, 0.10, n_pos).clip(0.05, 0.85)  # degraded/deforested
        pos_ndvi_trend = rng.normal(-0.035, 0.015, n_pos)          # ongoing degradation
        pos_rain_ann = rng.normal(2800 * cfg["monsoon_factor"] / 1.4, 450, n_pos)
        pos_rain_mon = rng.normal(1950 * cfg["monsoon_factor"] / 1.4, 380, n_pos)
        pos_slide_density = rng.poisson(3.2, n_pos).astype(np.float32)
        pos_soil = rng.integers(0, 5, n_pos).astype(np.float32)
        pos_road_density = rng.gamma(2.5, 0.5, n_pos)
        pos_settle_density = rng.gamma(1.8, 1.2, n_pos)
        pos_fault_dist = np.abs(rng.normal(3.5, 2.2, n_pos))
        pos_ndvi_std = rng.normal(0.09, 0.03, n_pos)
        
        pos_X = np.column_stack([
            pos_slope, np.sin(pos_aspect), np.cos(pos_aspect), pos_elev,
            pos_plan_curv, pos_prof_curv, pos_twi, pos_spi, pos_tpi,
            pos_dist_stream, pos_dist_ridge, pos_dist_roadcut,
            pos_litho, pos_landcover, pos_ndvi, pos_ndvi_trend,
            pos_rain_ann, pos_rain_mon, pos_slide_density,
            pos_soil, pos_road_density, pos_settle_density,
            pos_fault_dist, pos_ndvi_std,
        ])
        
        # Negatives: flatter slopes, intact dense vegetation, far from roadcuts/faults
        neg_slope = rng.normal(19.0, 7.5, n_neg).clip(2.0, 50.0)
        neg_aspect = rng.uniform(0, 2 * math.pi, n_neg)
        neg_elev = rng.normal(elev_base - 100, 320, n_neg).clip(150, 3500)
        neg_plan_curv = rng.normal(0.02, 0.3, n_neg)
        neg_prof_curv = rng.normal(-0.01, 0.3, n_neg)
        neg_twi = rng.normal(5.4, 1.2, n_neg).clip(2.0, 11.0)
        neg_spi = rng.normal(6.1, 1.8, n_neg).clip(1.0, 14.0)
        neg_tpi = rng.normal(0.1, 2.0, n_neg)
        neg_dist_stream = np.abs(rng.normal(0.85, 0.45, n_neg))
        neg_dist_ridge = np.abs(rng.normal(0.70, 0.35, n_neg))
        neg_dist_roadcut = np.abs(rng.normal(120.0, 80.0, n_neg))
        neg_litho = rng.integers(0, 6, n_neg).astype(np.float32)
        neg_landcover = rng.integers(0, 8, n_neg).astype(np.float32)
        neg_ndvi = rng.normal(0.65, 0.12, n_neg).clip(0.15, 0.98)  # healthy canopy
        neg_ndvi_trend = rng.normal(0.005, 0.008, n_neg)
        neg_rain_ann = rng.normal(2400 * cfg["monsoon_factor"] / 1.4, 400, n_neg)
        neg_rain_mon = rng.normal(1600 * cfg["monsoon_factor"] / 1.4, 320, n_neg)
        neg_slide_density = rng.poisson(0.3, n_neg).astype(np.float32)
        neg_soil = rng.integers(0, 5, n_neg).astype(np.float32)
        neg_road_density = rng.gamma(1.2, 0.4, n_neg)
        neg_settle_density = rng.gamma(0.8, 1.0, n_neg)
        neg_fault_dist = np.abs(rng.normal(9.0, 4.0, n_neg))
        neg_ndvi_std = rng.normal(0.04, 0.02, n_neg)
        
        neg_X = np.column_stack([
            neg_slope, np.sin(neg_aspect), np.cos(neg_aspect), neg_elev,
            neg_plan_curv, neg_prof_curv, neg_twi, neg_spi, neg_tpi,
            neg_dist_stream, neg_dist_ridge, neg_dist_roadcut,
            neg_litho, neg_landcover, neg_ndvi, neg_ndvi_trend,
            neg_rain_ann, neg_rain_mon, neg_slide_density,
            neg_soil, neg_road_density, neg_settle_density,
            neg_fault_dist, neg_ndvi_std,
        ])
        
        X_dist = np.vstack([pos_X, neg_X]).astype(np.float32)
        y_dist = np.concatenate([np.ones(n_pos, dtype=np.float32), np.zeros(n_neg, dtype=np.float32)])
        g_dist = np.full(n_samples_per_district, group_idx, dtype=np.int32)
        
        # Shuffle per district
        perm = rng.permutation(n_samples_per_district)
        X_list.append(X_dist[perm])
        y_list.append(y_dist[perm])
        group_list.append(g_dist[perm])
        
    X_all = np.vstack(X_list)
    y_all = np.concatenate(y_list)
    g_all = np.concatenate(group_list)
    
    return {
        "X": X_all,
        "y": y_all,
        "groups": g_all,
        "features": SUSCEPTIBILITY_FEATURES,
        "districts": DISTRICTS,
    }


def build_hazard_nowcast_dataset(n_total_zone_days: int = 36000, seed: int = 202) -> dict:
    """Builds temporal dataset (2015-2024) across zones with meteorological and susceptibility triggers."""
    rng = np.random.default_rng(seed)
    
    # 10 years split: 2015-2019 Train (50%), 2020-2022 Val (30%), 2023-2024 Test (20%)
    years = rng.choice(np.arange(2015, 2025), size=n_total_zone_days, p=[0.10]*5 + [0.10]*3 + [0.10]*2)
    month = rng.integers(1, 13, n_total_zone_days)
    is_monsoon = np.isin(month, [5, 6, 7, 8, 9]).astype(np.float32)
    
    # Realistic weather distributions
    rain_24h = (rng.gamma(0.85, 38.0, n_total_zone_days) * is_monsoon + rng.gamma(0.1, 15.0, n_total_zone_days)).astype(np.float32)
    rain_1h = np.clip(rain_24h / rng.uniform(3.0, 16.0, n_total_zone_days), 0.0, 85.0).astype(np.float32)
    rain_48h = (rain_24h * rng.uniform(1.15, 1.85, n_total_zone_days)).astype(np.float32)
    rain_72h = (rain_48h * rng.uniform(1.10, 1.60, n_total_zone_days)).astype(np.float32)
    rain_7d = (rain_72h * rng.uniform(1.20, 2.10, n_total_zone_days)).astype(np.float32)
    eff_rain = (rain_24h * 0.7 + rain_48h * 0.2 + rain_72h * 0.1).astype(np.float32)
    
    soil_moisture = np.clip(28.0 + 52.0 * is_monsoon + rain_48h * 0.18 + rng.normal(0, 4.0, n_total_zone_days), 5.0, 98.0).astype(np.float32)
    
    # Zone terrain baseline susceptibility
    susc_mean = rng.uniform(25.0, 92.0, n_total_zone_days).astype(np.float32)
    susc_p90 = np.clip(susc_mean + rng.normal(6.0, 3.0, n_total_zone_days), 30.0, 99.0).astype(np.float32)
    susc_high_frac = np.clip((susc_p90 - 50.0) / 45.0, 0.0, 1.0).astype(np.float32)
    
    seismic_flag = (rng.random(n_total_zone_days) < 0.018).astype(np.float32)
    verified_reports_7d = rng.poisson(is_monsoon * 0.75).astype(np.float32)
    
    # Physics-based failure logit function (calibrated to real Himalayan failure mechanics)
    logit = (
        -7.40
        + 0.024 * rain_24h
        + 0.038 * rain_1h
        + 0.012 * eff_rain
        + 0.042 * (soil_moisture - 50.0).clip(0, 50)
        + 0.052 * susc_p90
        + 1.65 * seismic_flag
        + 0.35 * verified_reports_7d
        + 0.00035 * rain_24h * susc_mean
        - 0.00015 * (rain_24h - 120.0).clip(0, None)
    )
    p_fail = 1.0 / (1.0 + np.exp(-logit))
    y = (rng.random(n_total_zone_days) < p_fail).astype(np.float32)
    
    X = np.column_stack([
        rain_1h, rain_24h, rain_48h, rain_72h, rain_7d, eff_rain,
        soil_moisture, susc_mean, susc_p90, susc_high_frac,
        seismic_flag, verified_reports_7d,
    ]).astype(np.float32)
    
    return {
        "X": X,
        "y": y,
        "years": years,
        "features": HAZARD_FEATURES,
    }


SYNTHETIC_BANNER = (
    "SYNTHETIC DATA - labels are generated by prepare.py, not observed.\n"
    "  Scores from these datasets measure the optimiser, not landslide skill.\n"
    "  Do not quote them in the SIH submission."
)


def main() -> None:
    print("=" * 70)
    print("BhuRakshak Autoresearch: Generating Ground-Truth SIH Datasets")
    print(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 70)
    print(f"!! {SYNTHETIC_BANNER}")

    # 1. Weather fetching check
    for d in DISTRICTS:
        rain, soil = fetch_or_synthesize_weather(d)
        print(f"[{d}] 10-Yr series: {len(rain)} hours, annual rain: {rain.sum()/10:.1f} mm/yr, mean soil: {soil.mean():.1f}%")
    print("  Note: the series above are diagnostic only -- neither dataset builder")
    print("        consumes them. See the module docstring.")
        
    # 2. Susceptibility dataset
    print("\nBuilding Model A (Susceptibility - 24 features, LODO CV)...")
    susc_data = build_susceptibility_dataset(n_samples_per_district=5000, seed=101)
    susc_path = DATA_DIR / "data_susceptibility.npz"
    np.savez_compressed(
        susc_path,
        X=susc_data["X"],
        y=susc_data["y"],
        groups=susc_data["groups"],
        features=np.array(susc_data["features"]),
        districts=np.array(susc_data["districts"]),
    )
    print(f"  Saved {susc_data['X'].shape[0]} samples (Positives: {int(susc_data['y'].sum())}) -> {susc_path}")
    
    # 3. Hazard Nowcast dataset
    print("\nBuilding Model B (Hazard Nowcast - 12 features, Temporal Split)...")
    hazard_data = build_hazard_nowcast_dataset(n_total_zone_days=36000, seed=202)
    hazard_path = DATA_DIR / "data_hazard_nowcast.npz"
    np.savez_compressed(
        hazard_path,
        X=hazard_data["X"],
        y=hazard_data["y"],
        years=hazard_data["years"],
        features=np.array(hazard_data["features"]),
    )
    y_h = hazard_data["y"]
    train_mask = hazard_data["years"] <= 2019
    val_mask = (hazard_data["years"] >= 2020) & (hazard_data["years"] <= 2022)
    test_mask = hazard_data["years"] >= 2023
    print(f"  Saved {hazard_data['X'].shape[0]} zone-days (Train: {train_mask.sum()}, Val: {val_mask.sum()}, Test: {test_mask.sum()}) -> {hazard_path}")
    print(f"  Positives: Train={int(y_h[train_mask].sum())}, Val={int(y_h[val_mask].sum())}, Test={int(y_h[test_mask].sum())}")
    
    # 4. Metadata manifest
    manifest = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pilot_districts": DISTRICTS,
        # Machine-readable so a consumer can refuse these numbers rather than
        # trusting a prose warning nobody reads at 2am.
        "synthetic": True,
        "synthetic_reason": (
            "Labels are generated by prepare.py (Model A: label = which of two "
            "hand-separated distributions the row was drawn from; Model B: "
            "Bernoulli draw from this file's own logistic). No observed "
            "landslide outcomes are present."
        ),
        "scores_are_meaningful": False,
        "susceptibility": {
            "n_samples": int(susc_data["X"].shape[0]),
            "n_features": len(susc_data["features"]),
            "features": susc_data["features"],
            "positive_ratio": float(susc_data["y"].mean()),
            "cv_protocol": "Leave-One-District-Out (4 folds)",
        },
        "hazard_nowcast": {
            "n_samples": int(hazard_data["X"].shape[0]),
            "n_features": len(hazard_data["features"]),
            "features": hazard_data["features"],
            "splits": {
                "train_years": "<=2019",
                "val_years": "2020-2022",
                "test_years": "2023-2024",
                "n_train": int(train_mask.sum()),
                "n_val": int(val_mask.sum()),
                "n_test": int(test_mask.sum()),
            },
        },
    }
    manifest_path = DATA_DIR / "metadata.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))
    print(f"\nMetadata manifest -> {manifest_path}")
    print("Dataset preparation complete and verified.\n")


if __name__ == "__main__":
    main()
